Mox.defmock(ElasticsearchMock, for: Elasticsearch.API)
Mox.defmock(MockClusterHandler, for: TdCluster.ClusterHandlerBehaviour)
TdCache.Redix.del!()
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(TdDd.Repo, :manual)
