variables:
  VERSION: "7.12.1" # used for alpha builds
  APP_NAME: "td_dd"
  COMPOSE_FILE: "ci/docker-compose.yml"
  COMPOSE_PROJECT_NAME: "${APP_NAME}_${CI_JOB_ID}"
  # See also variables set in ci/env.sh

stages:
  - deploy

before_script:
  - source ci/env.sh ecr-login

publish:branches:
  stage: deploy
  except:
    - develop
    - main
    - tags
  tags:
    - docker
  script:
    - docker-compose run --rm release
    - docker build --build-arg APP_NAME=${APP_NAME} --build-arg APP_VERSION=${APP_VERSION} -t ${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} .
    - docker tag ${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
    - docker push ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
