variables:
  VERSION: "7.12.1" # used for alpha builds
  APP_NAME: "td_dd"
  COMPOSE_FILE: "ci/docker-compose.yml"
  COMPOSE_PROJECT_NAME: "${APP_NAME}_${CI_JOB_ID}"
  # See also variables set in ci/env.sh

stages:
  - build
  - test
  - publish
  - acceptance
  - deploy

before_script:
  - source ci/env.sh ecr-login

deps:
  stage: build
  tags:
    - docker-compose
  script:
    - docker-compose run --rm build
  after_script:
    - docker-compose down -v
  artifacts:
    paths:
      - deps/
      - _build/test/

release:
  stage: build
  needs:
    - deps
  tags:
    - docker-compose
  script:
    - docker-compose run --rm release
  after_script:
    - docker-compose down -v
  artifacts:
    paths:
      - _build/prod/*.tar.gz

publish:branches:
  stage: deploy
  except:
    - develop
    - main
    - tags
  when: manual
  tags:
    - docker
  script:
    - docker build --build-arg APP_NAME=${APP_NAME} --build-arg APP_VERSION=${APP_VERSION} -t ${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} .
    - docker tag ${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
    - docker push ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
