{application,phoenix_ecto,
             [{description,"Integration between Phoenix & Ecto"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Phoenix.Ecto.SQL.Sandbox',
                        'Elixir.Phoenix.Ecto.SQL.SandboxSession',
                        'Elixir.Phoenix.Ecto.SQL.SandboxSupervisor',
                        'Elixir.Plug.Exception.Ecto.CastError',
                        'Elixir.Plug.Exception.Ecto.InvalidChangesetError',
                        'Elixir.Plug.Exception.Ecto.NoResultsError',
                        'Elixir.Plug.Exception.Ecto.Query.CastError']},
              {registered,[]},
              {vsn,"3.3.0"},
              {mod,{'Elixir.Phoenix.Ecto',[]}},
              {applications,[kernel,stdlib,elixir,logger,ecto,plug]},
              {env,[{exclude_ecto_exceptions_from_plug,[]}]}]}.
