# Use postgres/example user/password credentials
version: "3.4"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - cluster.name=truedat
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: curl --silent http://localhost:9200/_cat/health?h=status | grep -q -E green\|yellow || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:9.6.10-alpine
    restart: always
    healthcheck:
      test: echo "SELECT 1" | psql --username postgres --quiet --no-align --tuples-only | grep -q 1 || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: library/redis:5.0-alpine
    command: redis-server --appendonly yes
    healthcheck:
      test: redis-cli -h localhost ping | grep -q PONG || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  build:
    image: bluetab/elixir:1.10.1-alpine-20200212171042
    command: ci/build.sh
    environment:
      APP_VERSION: "${APP_VERSION}"
      HOME: /tmp # CURRENT_UID doesn't have a home
      MIX_ENV: prod
      MIX_HOME: /code/.mix
    user: ${CURRENT_UID-0:0}
    working_dir: /code
    volumes:
      - "${CI_PROJECT_DIR}:/code"

  test:
    image: bluetab/elixir:1.10.1-alpine-20200212171042
    command: ci/test.sh
    environment:
      HOME: /tmp # CURRENT_UID doesn't have a home
      MIX_ENV: test
      MIX_HOME: /code/.mix
    working_dir: /code
    user: ${CURRENT_UID-0:0}
    volumes:
      - "${CI_PROJECT_DIR}:/code"
    depends_on:
      - postgres
      - redis

  service:
    image: ${ECR}/${ECR_NAMESPACE}/${CI_PROJECT_NAME}:${APP_VERSION}
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_USER: postgres
      ES_URL: http://elastic:9200
      GUARDIAN_SECRET_KEY: topsecret
      IMPORT_DIR: /import
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
      - elastic

  wait_for_elastic:
    image: bluetab/wait-for:20190507133127
    command: elastic:9200 -t 60 -- curl --silent elastic:9200
    depends_on:
      - elastic

  acceptance:
    image: bluetab/wait-for:20190507133127
    command: service:4005 -t 30 -- curl --silent service:4005/api/ping
    depends_on:
      - service
